pull_request_rules:
  - name: Auto-merge for Dependabot pull requests
    conditions:
      - author=dependabot[bot]
      - check-success=Nix / Run Checks
      - check-success=Nix Unstable / Run Checks
      - check-success=Nix Impure / Run Checks
    actions:
      merge:
        method: squash
