pull_request_rules:
  - name: Auto-merge for Dependabot pull requests
    conditions:
      - author=dependabot[bot]
      - check-success=Nix / Success
      - check-success=Unstable Nix / Success
      - check-success=Impure Nix / Success
    actions:
      merge:
        method: squash
