pull_request_rules:
  - name: Auto-merge for Dependabot pull requests
    conditions:
      - author=dependabot[bot]
      - 'check-success=Success: Nix'
#      - 'check-success=Success: Unstable Nix'
      - 'check-success=Success: Impure Nix'
    actions:
      merge:
        method: squash
