pull_request_rules:
  - name: Auto-merge for Dependabot pull requests
    conditions:
      - author=dependabot[bot]
      - check-success=Stable Flake Build
      - check-success=Stable Impure Build
      - check-success=Unstable Flake Build
    actions:
      merge:
        method: squash
