#!/usr/bin/env nix-shell
#!nix-shell update-shell.nix -i python3

# Derived from https://github.com/NixOS/nixpkgs under the following license:
#   Copyright (c) 2003-2021 Eelco Dolstra and the Nixpkgs/NixOS contributors
#
#   Permission is hereby granted, free of charge, to any person obtaining
#   a copy of this software and associated documentation files (the
#   "Software"), to deal in the Software without restriction, including
#   without limitation the rights to use, copy, modify, merge, publish,
#   distribute, sublicense, and/or sell copies of the Software, and to
#   permit persons to whom the Software is furnished to do so, subject to
#   the following conditions:
#
#   The above copyright notice and this permission notice shall be
#   included in all copies or substantial portions of the Software.
#
#   THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
#   EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
#   MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
#   NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
#   LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
#   OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
#   WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

# run with:
# $ nix run .\#vimPluginsUpdater
# format:
# $ nix run nixpkgs#python3Packages.ruff -- update.py
# type-check:
# $ nix run nixpkgs#python3Packages.mypy -- update.py
# linted:
# $ nix run nixpkgs#python3Packages.flake8 -- --ignore E501,E265,E402 update.py

# If you see `HTTP Error 429: too many requests` errors while running this
# script, refer to:
#
# https://github.com/NixOS/nixpkgs/blob/master/doc/languages-frameworks/vim.section.md#updating-plugins-in-nixpkgs-updating-plugins-in-nixpkgs
#
# (or the equivalent file /doc/languages-frameworks/vim.section.md
# from Nixpkgs master tree).
#

import inspect
import logging
import os
import textwrap
from pathlib import Path
from typing import List, Tuple

log = logging.getLogger("vim-updater")

ROOT = Path(os.path.dirname(os.path.abspath(inspect.getfile(inspect.currentframe()))))

import nixpkgs_plugin_update
from nixpkgs_plugin_update import PluginDesc, run_nix_expr


HEADER = (
    "# GENERATED by ./pkgs/vim-plugins/utils/update.py. Do not edit!"
)


class VimEditor(nixpkgs_plugin_update.Editor):
    def generate_nix(
        self, plugins: List[Tuple[PluginDesc, nixpkgs_plugin_update.Plugin]], outfile: str
    ):
        log.info("Generating nix code")

        GET_PLUGINS_LUA = """
        let localpkgs = import <localpkgs> {}; in
        builtins.attrNames localpkgs.lua51Packages or {}"""
        log.debug("Loading list of lua plugins...")
        luaPlugins = run_nix_expr(GET_PLUGINS_LUA, self.nixpkgs, timeout=30)

        def _isNeovimPlugin(plug: nixpkgs_plugin_update.Plugin) -> bool:
            """
            Whether it's a neovim-only plugin
            We can check if it's available in lua packages
            """
            if plug.normalized_name in luaPlugins:
                log.debug("%s is a neovim plugin", plug)
                return True
            return False

        with open(outfile, "w+") as f:
            log.debug("Writing to %s", outfile)
            f.write(HEADER)
            f.write(
                textwrap.dedent(
                    """
                {
                  lib,
                  buildVimPlugin,
                  buildNeovimPlugin,
                  fetchFromGitHub,
                }:

                final: prev: {
                """
                )
            )
            for pdesc, plugin in plugins:
                content = self.plugin2nix(pdesc, plugin, _isNeovimPlugin(plugin))
                f.write(content)
            f.write("}\n")
        print(f"updated {outfile}")

    def plugin2nix(
        self, pdesc: PluginDesc, plugin: nixpkgs_plugin_update.Plugin, isNeovim: bool
    ) -> str:
        if isNeovim:
            raise RuntimeError(f"Plugin {plugin.name} is already packaged in `luaPackages`, please use that")
        repo = pdesc.repo

        content = f"  {plugin.normalized_name} = "
        src_nix = repo.as_nix(plugin)
        content += """{buildFn} {{
    pname = "{plugin.name}";
    version = "{plugin.version}";
    src = {src_nix};
    meta.homepage = "{repo.uri}";
    meta.hydraPlatforms = [ ];
  }};

""".format(
            buildFn="buildNeovimPlugin" if isNeovim else "buildVimPlugin",
            plugin=plugin,
            src_nix=src_nix,
            repo=repo,
        )
        log.debug(content)
        return content

    def update(self, args):
        nixpkgs_plugin_update.update_plugins(self, args)


def main():
    global luaPlugins

    log.debug(f"Loading from {ROOT}/get-plugins.nix")
    with open(f"{ROOT}/get-plugins.nix") as f:
        GET_PLUGINS = f.read()
    editor = VimEditor(
        "vim", Path("pkgs/vim-plugins"), GET_PLUGINS
    )
    editor.run()


if __name__ == "__main__":
    main()
