{ config, lib, pkgs, ... }:

lib.mkIf config.foosteros.profiles.fonts {
  fonts.packages = with pkgs; [
    aileron
    noto-fonts noto-fonts-cjk-sans noto-fonts-emoji
    dejavu_fonts
    freefont_ttf
    gyre-fonts
    liberation_ttf
    roboto comfortaa
  ];

  fonts.fontconfig.localConf = ''
    <?xml version="1.0"?>
    <!DOCTYPE fontconfig SYSTEM "urn:fontconfig:fonts.dtd">
    <fontconfig>
      <description>Remove Unicode-recommended emoji from non-emoji fonts</description>
      <match target="scan">
        <test name="family" compare="not_contains">
          <string>Emoji</string>
        </test>
        <edit name="charset" mode="assign" binding="same">
          <minus>
            <name>charset</name>
            <charset>
              <!-- Generated from Unicode 15.1 UTS#51 dataset -->
              <range>
                <int>0x231a</int>
                <int>0x231b</int>
              </range>
              <range>
                <int>0x23e9</int>
                <int>0x23ec</int>
              </range>
              <int>0x23f0</int>
              <int>0x23f3</int>
              <range>
                <int>0x25fd</int>
                <int>0x25fe</int>
              </range>
              <range>
                <int>0x2614</int>
                <int>0x2615</int>
              </range>
              <range>
                <int>0x2648</int>
                <int>0x2653</int>
              </range>
              <int>0x267f</int>
              <int>0x2693</int>
              <int>0x26a1</int>
              <range>
                <int>0x26aa</int>
                <int>0x26ab</int>
              </range>
              <range>
                <int>0x26bd</int>
                <int>0x26be</int>
              </range>
              <range>
                <int>0x26c4</int>
                <int>0x26c5</int>
              </range>
              <int>0x26ce</int>
              <int>0x26d4</int>
              <int>0x26ea</int>
              <range>
                <int>0x26f2</int>
                <int>0x26f3</int>
              </range>
              <int>0x26f5</int>
              <int>0x26fa</int>
              <int>0x26fd</int>
              <int>0x2705</int>
              <range>
                <int>0x270a</int>
                <int>0x270b</int>
              </range>
              <int>0x2728</int>
              <int>0x274c</int>
              <int>0x274e</int>
              <range>
                <int>0x2753</int>
                <int>0x2755</int>
              </range>
              <int>0x2757</int>
              <range>
                <int>0x2795</int>
                <int>0x2797</int>
              </range>
              <int>0x27b0</int>
              <int>0x27bf</int>
              <range>
                <int>0x2b1b</int>
                <int>0x2b1c</int>
              </range>
              <int>0x2b50</int>
              <int>0x2b55</int>
              <int>0x1f004</int>
              <int>0x1f0cf</int>
              <int>0x1f18e</int>
              <range>
                <int>0x1f191</int>
                <int>0x1f19a</int>
              </range>
              <int>0x1f201</int>
              <int>0x1f21a</int>
              <int>0x1f22f</int>
              <range>
                <int>0x1f232</int>
                <int>0x1f236</int>
              </range>
              <range>
                <int>0x1f238</int>
                <int>0x1f23a</int>
              </range>
              <range>
                <int>0x1f250</int>
                <int>0x1f251</int>
              </range>
              <range>
                <int>0x1f300</int>
                <int>0x1f30c</int>
              </range>
              <range>
                <int>0x1f30d</int>
                <int>0x1f30e</int>
              </range>
              <int>0x1f30f</int>
              <int>0x1f310</int>
              <int>0x1f311</int>
              <int>0x1f312</int>
              <range>
                <int>0x1f313</int>
                <int>0x1f315</int>
              </range>
              <range>
                <int>0x1f316</int>
                <int>0x1f318</int>
              </range>
              <int>0x1f319</int>
              <int>0x1f31a</int>
              <int>0x1f31b</int>
              <int>0x1f31c</int>
              <range>
                <int>0x1f31d</int>
                <int>0x1f31e</int>
              </range>
              <range>
                <int>0x1f31f</int>
                <int>0x1f320</int>
              </range>
              <range>
                <int>0x1f32d</int>
                <int>0x1f32f</int>
              </range>
              <range>
                <int>0x1f330</int>
                <int>0x1f331</int>
              </range>
              <range>
                <int>0x1f332</int>
                <int>0x1f333</int>
              </range>
              <range>
                <int>0x1f334</int>
                <int>0x1f335</int>
              </range>
              <range>
                <int>0x1f337</int>
                <int>0x1f34a</int>
              </range>
              <int>0x1f34b</int>
              <range>
                <int>0x1f34c</int>
                <int>0x1f34f</int>
              </range>
              <int>0x1f350</int>
              <range>
                <int>0x1f351</int>
                <int>0x1f37b</int>
              </range>
              <int>0x1f37c</int>
              <range>
                <int>0x1f37e</int>
                <int>0x1f37f</int>
              </range>
              <range>
                <int>0x1f380</int>
                <int>0x1f393</int>
              </range>
              <range>
                <int>0x1f3a0</int>
                <int>0x1f3c4</int>
              </range>
              <int>0x1f3c5</int>
              <int>0x1f3c6</int>
              <int>0x1f3c7</int>
              <int>0x1f3c8</int>
              <int>0x1f3c9</int>
              <int>0x1f3ca</int>
              <range>
                <int>0x1f3cf</int>
                <int>0x1f3d3</int>
              </range>
              <range>
                <int>0x1f3e0</int>
                <int>0x1f3e3</int>
              </range>
              <int>0x1f3e4</int>
              <range>
                <int>0x1f3e5</int>
                <int>0x1f3f0</int>
              </range>
              <int>0x1f3f4</int>
              <range>
                <int>0x1f3f8</int>
                <int>0x1f407</int>
              </range>
              <int>0x1f408</int>
              <range>
                <int>0x1f409</int>
                <int>0x1f40b</int>
              </range>
              <range>
                <int>0x1f40c</int>
                <int>0x1f40e</int>
              </range>
              <range>
                <int>0x1f40f</int>
                <int>0x1f410</int>
              </range>
              <range>
                <int>0x1f411</int>
                <int>0x1f412</int>
              </range>
              <int>0x1f413</int>
              <int>0x1f414</int>
              <int>0x1f415</int>
              <int>0x1f416</int>
              <range>
                <int>0x1f417</int>
                <int>0x1f429</int>
              </range>
              <int>0x1f42a</int>
              <range>
                <int>0x1f42b</int>
                <int>0x1f43e</int>
              </range>
              <int>0x1f440</int>
              <range>
                <int>0x1f442</int>
                <int>0x1f464</int>
              </range>
              <int>0x1f465</int>
              <range>
                <int>0x1f466</int>
                <int>0x1f46b</int>
              </range>
              <range>
                <int>0x1f46c</int>
                <int>0x1f46d</int>
              </range>
              <range>
                <int>0x1f46e</int>
                <int>0x1f4ac</int>
              </range>
              <int>0x1f4ad</int>
              <range>
                <int>0x1f4ae</int>
                <int>0x1f4b5</int>
              </range>
              <range>
                <int>0x1f4b6</int>
                <int>0x1f4b7</int>
              </range>
              <range>
                <int>0x1f4b8</int>
                <int>0x1f4eb</int>
              </range>
              <range>
                <int>0x1f4ec</int>
                <int>0x1f4ed</int>
              </range>
              <int>0x1f4ee</int>
              <int>0x1f4ef</int>
              <range>
                <int>0x1f4f0</int>
                <int>0x1f4f4</int>
              </range>
              <int>0x1f4f5</int>
              <range>
                <int>0x1f4f6</int>
                <int>0x1f4f7</int>
              </range>
              <int>0x1f4f8</int>
              <range>
                <int>0x1f4f9</int>
                <int>0x1f4fc</int>
              </range>
              <range>
                <int>0x1f4ff</int>
                <int>0x1f502</int>
              </range>
              <int>0x1f503</int>
              <range>
                <int>0x1f504</int>
                <int>0x1f507</int>
              </range>
              <int>0x1f508</int>
              <int>0x1f509</int>
              <range>
                <int>0x1f50a</int>
                <int>0x1f514</int>
              </range>
              <int>0x1f515</int>
              <range>
                <int>0x1f516</int>
                <int>0x1f52b</int>
              </range>
              <range>
                <int>0x1f52c</int>
                <int>0x1f52d</int>
              </range>
              <range>
                <int>0x1f52e</int>
                <int>0x1f53d</int>
              </range>
              <range>
                <int>0x1f54b</int>
                <int>0x1f54e</int>
              </range>
              <range>
                <int>0x1f550</int>
                <int>0x1f55b</int>
              </range>
              <range>
                <int>0x1f55c</int>
                <int>0x1f567</int>
              </range>
              <int>0x1f57a</int>
              <range>
                <int>0x1f595</int>
                <int>0x1f596</int>
              </range>
              <int>0x1f5a4</int>
              <range>
                <int>0x1f5fb</int>
                <int>0x1f5ff</int>
              </range>
              <int>0x1f600</int>
              <range>
                <int>0x1f601</int>
                <int>0x1f606</int>
              </range>
              <range>
                <int>0x1f607</int>
                <int>0x1f608</int>
              </range>
              <range>
                <int>0x1f609</int>
                <int>0x1f60d</int>
              </range>
              <int>0x1f60e</int>
              <int>0x1f60f</int>
              <int>0x1f610</int>
              <int>0x1f611</int>
              <range>
                <int>0x1f612</int>
                <int>0x1f614</int>
              </range>
              <int>0x1f615</int>
              <int>0x1f616</int>
              <int>0x1f617</int>
              <int>0x1f618</int>
              <int>0x1f619</int>
              <int>0x1f61a</int>
              <int>0x1f61b</int>
              <range>
                <int>0x1f61c</int>
                <int>0x1f61e</int>
              </range>
              <int>0x1f61f</int>
              <range>
                <int>0x1f620</int>
                <int>0x1f625</int>
              </range>
              <range>
                <int>0x1f626</int>
                <int>0x1f627</int>
              </range>
              <range>
                <int>0x1f628</int>
                <int>0x1f62b</int>
              </range>
              <int>0x1f62c</int>
              <int>0x1f62d</int>
              <range>
                <int>0x1f62e</int>
                <int>0x1f62f</int>
              </range>
              <range>
                <int>0x1f630</int>
                <int>0x1f633</int>
              </range>
              <int>0x1f634</int>
              <int>0x1f635</int>
              <int>0x1f636</int>
              <range>
                <int>0x1f637</int>
                <int>0x1f640</int>
              </range>
              <range>
                <int>0x1f641</int>
                <int>0x1f644</int>
              </range>
              <range>
                <int>0x1f645</int>
                <int>0x1f64f</int>
              </range>
              <int>0x1f680</int>
              <range>
                <int>0x1f681</int>
                <int>0x1f682</int>
              </range>
              <range>
                <int>0x1f683</int>
                <int>0x1f685</int>
              </range>
              <int>0x1f686</int>
              <int>0x1f687</int>
              <int>0x1f688</int>
              <int>0x1f689</int>
              <range>
                <int>0x1f68a</int>
                <int>0x1f68b</int>
              </range>
              <int>0x1f68c</int>
              <int>0x1f68d</int>
              <int>0x1f68e</int>
              <int>0x1f68f</int>
              <int>0x1f690</int>
              <range>
                <int>0x1f691</int>
                <int>0x1f693</int>
              </range>
              <int>0x1f694</int>
              <int>0x1f695</int>
              <int>0x1f696</int>
              <int>0x1f697</int>
              <int>0x1f698</int>
              <range>
                <int>0x1f699</int>
                <int>0x1f69a</int>
              </range>
              <range>
                <int>0x1f69b</int>
                <int>0x1f6a1</int>
              </range>
              <int>0x1f6a2</int>
              <int>0x1f6a3</int>
              <range>
                <int>0x1f6a4</int>
                <int>0x1f6a5</int>
              </range>
              <int>0x1f6a6</int>
              <range>
                <int>0x1f6a7</int>
                <int>0x1f6ad</int>
              </range>
              <range>
                <int>0x1f6ae</int>
                <int>0x1f6b1</int>
              </range>
              <int>0x1f6b2</int>
              <range>
                <int>0x1f6b3</int>
                <int>0x1f6b5</int>
              </range>
              <int>0x1f6b6</int>
              <range>
                <int>0x1f6b7</int>
                <int>0x1f6b8</int>
              </range>
              <range>
                <int>0x1f6b9</int>
                <int>0x1f6be</int>
              </range>
              <int>0x1f6bf</int>
              <int>0x1f6c0</int>
              <range>
                <int>0x1f6c1</int>
                <int>0x1f6c5</int>
              </range>
              <int>0x1f6cc</int>
              <int>0x1f6d0</int>
              <range>
                <int>0x1f6d1</int>
                <int>0x1f6d2</int>
              </range>
              <int>0x1f6d5</int>
              <range>
                <int>0x1f6d6</int>
                <int>0x1f6d7</int>
              </range>
              <int>0x1f6dc</int>
              <range>
                <int>0x1f6dd</int>
                <int>0x1f6df</int>
              </range>
              <range>
                <int>0x1f6eb</int>
                <int>0x1f6ec</int>
              </range>
              <range>
                <int>0x1f6f4</int>
                <int>0x1f6f6</int>
              </range>
              <range>
                <int>0x1f6f7</int>
                <int>0x1f6f8</int>
              </range>
              <int>0x1f6f9</int>
              <int>0x1f6fa</int>
              <range>
                <int>0x1f6fb</int>
                <int>0x1f6fc</int>
              </range>
              <range>
                <int>0x1f7e0</int>
                <int>0x1f7eb</int>
              </range>
              <int>0x1f7f0</int>
              <int>0x1f90c</int>
              <range>
                <int>0x1f90d</int>
                <int>0x1f90f</int>
              </range>
              <range>
                <int>0x1f910</int>
                <int>0x1f918</int>
              </range>
              <range>
                <int>0x1f919</int>
                <int>0x1f91e</int>
              </range>
              <int>0x1f91f</int>
              <range>
                <int>0x1f920</int>
                <int>0x1f927</int>
              </range>
              <range>
                <int>0x1f928</int>
                <int>0x1f92f</int>
              </range>
              <int>0x1f930</int>
              <range>
                <int>0x1f931</int>
                <int>0x1f932</int>
              </range>
              <range>
                <int>0x1f933</int>
                <int>0x1f93a</int>
              </range>
              <range>
                <int>0x1f93c</int>
                <int>0x1f93e</int>
              </range>
              <int>0x1f93f</int>
              <range>
                <int>0x1f940</int>
                <int>0x1f945</int>
              </range>
              <range>
                <int>0x1f947</int>
                <int>0x1f94b</int>
              </range>
              <int>0x1f94c</int>
              <range>
                <int>0x1f94d</int>
                <int>0x1f94f</int>
              </range>
              <range>
                <int>0x1f950</int>
                <int>0x1f95e</int>
              </range>
              <range>
                <int>0x1f95f</int>
                <int>0x1f96b</int>
              </range>
              <range>
                <int>0x1f96c</int>
                <int>0x1f970</int>
              </range>
              <int>0x1f971</int>
              <int>0x1f972</int>
              <range>
                <int>0x1f973</int>
                <int>0x1f976</int>
              </range>
              <range>
                <int>0x1f977</int>
                <int>0x1f978</int>
              </range>
              <int>0x1f979</int>
              <int>0x1f97a</int>
              <int>0x1f97b</int>
              <range>
                <int>0x1f97c</int>
                <int>0x1f97f</int>
              </range>
              <range>
                <int>0x1f980</int>
                <int>0x1f984</int>
              </range>
              <range>
                <int>0x1f985</int>
                <int>0x1f991</int>
              </range>
              <range>
                <int>0x1f992</int>
                <int>0x1f997</int>
              </range>
              <range>
                <int>0x1f998</int>
                <int>0x1f9a2</int>
              </range>
              <range>
                <int>0x1f9a3</int>
                <int>0x1f9a4</int>
              </range>
              <range>
                <int>0x1f9a5</int>
                <int>0x1f9aa</int>
              </range>
              <range>
                <int>0x1f9ab</int>
                <int>0x1f9ad</int>
              </range>
              <range>
                <int>0x1f9ae</int>
                <int>0x1f9af</int>
              </range>
              <range>
                <int>0x1f9b0</int>
                <int>0x1f9b9</int>
              </range>
              <range>
                <int>0x1f9ba</int>
                <int>0x1f9bf</int>
              </range>
              <int>0x1f9c0</int>
              <range>
                <int>0x1f9c1</int>
                <int>0x1f9c2</int>
              </range>
              <range>
                <int>0x1f9c3</int>
                <int>0x1f9ca</int>
              </range>
              <int>0x1f9cb</int>
              <int>0x1f9cc</int>
              <range>
                <int>0x1f9cd</int>
                <int>0x1f9cf</int>
              </range>
              <range>
                <int>0x1f9d0</int>
                <int>0x1f9e6</int>
              </range>
              <range>
                <int>0x1f9e7</int>
                <int>0x1f9ff</int>
              </range>
              <range>
                <int>0x1fa70</int>
                <int>0x1fa73</int>
              </range>
              <int>0x1fa74</int>
              <range>
                <int>0x1fa75</int>
                <int>0x1fa77</int>
              </range>
              <range>
                <int>0x1fa78</int>
                <int>0x1fa7a</int>
              </range>
              <range>
                <int>0x1fa7b</int>
                <int>0x1fa7c</int>
              </range>
              <range>
                <int>0x1fa80</int>
                <int>0x1fa82</int>
              </range>
              <range>
                <int>0x1fa83</int>
                <int>0x1fa86</int>
              </range>
              <range>
                <int>0x1fa87</int>
                <int>0x1fa88</int>
              </range>
              <range>
                <int>0x1fa90</int>
                <int>0x1fa95</int>
              </range>
              <range>
                <int>0x1fa96</int>
                <int>0x1faa8</int>
              </range>
              <range>
                <int>0x1faa9</int>
                <int>0x1faac</int>
              </range>
              <range>
                <int>0x1faad</int>
                <int>0x1faaf</int>
              </range>
              <range>
                <int>0x1fab0</int>
                <int>0x1fab6</int>
              </range>
              <range>
                <int>0x1fab7</int>
                <int>0x1faba</int>
              </range>
              <range>
                <int>0x1fabb</int>
                <int>0x1fabd</int>
              </range>
              <int>0x1fabf</int>
              <range>
                <int>0x1fac0</int>
                <int>0x1fac2</int>
              </range>
              <range>
                <int>0x1fac3</int>
                <int>0x1fac5</int>
              </range>
              <range>
                <int>0x1face</int>
                <int>0x1facf</int>
              </range>
              <range>
                <int>0x1fad0</int>
                <int>0x1fad6</int>
              </range>
              <range>
                <int>0x1fad7</int>
                <int>0x1fad9</int>
              </range>
              <range>
                <int>0x1fada</int>
                <int>0x1fadb</int>
              </range>
              <range>
                <int>0x1fae0</int>
                <int>0x1fae7</int>
              </range>
              <int>0x1fae8</int>
              <range>
                <int>0x1faf0</int>
                <int>0x1faf6</int>
              </range>
              <range>
                <int>0x1faf7</int>
                <int>0x1faf8</int>
              </range>
            </charset>
          </minus>
        </edit>
      </match>
    </fontconfig>
  '';
}
