[
  ./adb.nix
  ./alien.nix
  ./azure.nix
  ./base.nix
  ./bluetooth.nix
  ./builders.nix
  ./cad.nix
  ./cosmic.nix
  ./ephemeral.nix
  ./fcitx5.nix
  ./fish.nix
  ./fonts.nix
  ./fwupd.nix
  ./gc.nix
  ./gnupg.nix
  ./grub.nix
  ./hibernate.nix
  ./homebins.nix
  ./hyfetch.nix
  ./ledger.nix
  ./libvirt.nix
  ./lily.nix
  ./lsp.nix
  ./miracast.nix
  ./music.nix
  ./neovim.nix
  ./networkd.nix
  ./networkmanager.nix
  ./nullmailer.nix
  ./pass.nix
  ./pipewire.nix
  ./pki.nix
  ./playdate.nix
  ./podman.nix
  ./printing.nix
  ./production.nix
  ./restic.nix
  ./sd-boot.nix
  ./secureboot.nix
  ./sway.nix
  ./sysrq.nix
  ./tex.nix
  ./tkey.nix
  ./tlp.nix
  ./tmux.nix
  ./udiskie.nix
  ./vps.nix
  ./workstation.nix
]
