# This file has been generated by ./misc/fish-plugins/update.py. Do not edit!
{ fetchFromGitHub }:

[
  {
    name = "done";
    src = fetchFromGitHub {
      owner = "franciscolourenco";
      repo = "done";
      rev = "4503af92f5425b4169d3915f7c9297437f42bfe1";
      sha256 = "0blw12azcq8f5fd26lyfd6bshg60b1ra9ldcpmb8jk7c7ban7ynp";
    };
  }

  {
    name = "humanize-duration";
    src = fetchFromGitHub {
      owner = "fishpkg";
      repo = "fish-humanize-duration";
      rev = "245e38ff3c03654271039f119078b721b7a26d3b";
      sha256 = "078wzrppw62dz297860n2qdljnnpmhpaj60gw5cl4dbfcij24335";
    };
  }

]
