[
  ./boot/systemd-boot.nix
  ./hardware/playdate.nix
  ./programs/kanshi.nix
  ./programs/mako.nix
  ./programs/sway.nix
  ./services/dnsimple-ddns.nix
  ./services/logmail.nix
  ./services/swaynag-battery.nix
]
