[
  ./hardware/playdate.nix
  ./hardware/tkey.nix
  ./programs/kanshi.nix
  ./programs/mako.nix
  ./programs/sway.nix
  ./programs/sway-assign-cgroups.nix
  ./programs/swayidle.nix
  ./programs/swaynag-battery.nix
  ./programs/swaywsr.nix
  ./programs/tkey-ssh-agent.nix
  ./services/dnsimple-ddns.nix
  ./services/logmail.nix
  ./system/devices.nix
]
