# Generated by update.sh
{ fetchurl }:

{
  "curl-7.84.0.tar.xz" = fetchurl {
    url = "https://curl.se/download/curl-7.84.0.tar.xz";
    hash = "sha256-LRGLQ/VHv+W66AbY1HtOWW6lslpsHwgK70n7zYF8Xbg=";
  };

  "brotli-1.0.9.tar.gz" = fetchurl {
    url = "https://github.com/google/brotli/archive/refs/tags/v1.0.9.tar.gz";
    hash = "sha256-+ejYHQQFumbRgVKa9CozVPg4yTkJX/mZMNpqqc32/kY=";
  };

  "nss-3.77.tar.gz" = fetchurl {
    url = "https://ftp.mozilla.org/pub/security/nss/releases/NSS_3_77_RTM/src/nss-3.77-with-nspr-4.32.tar.gz";
    hash = "sha256-j6UEIeWcTk5x0Z8j3WV3uK+xwT4vm38OyxpVrjd1KV8=";
  };

  "boringssl.zip" = fetchurl {
    url = "https://github.com/google/boringssl/archive/3a667d10e94186fd503966f5638e134fe9fb4080.zip";
    hash = "sha256-HsDIkd1x5IH49fUF07dJaabMIMsQygW+NI7GneULpA8=";
  };

  "nghttp2-1.46.0.tar.bz2" = fetchurl {
    url = "https://github.com/nghttp2/nghttp2/releases/download/v1.46.0/nghttp2-1.46.0.tar.bz2";
    hash = "sha256-moKXjIcAcbdp8n0riBkct3/clFpRwdaFx/YafhP8Ryk=";
  };
}
