name: Dependabot

on:
  pull_request:

permissions:
  pull-requests: write
  contents: write

jobs:
  merge:
    name: Auto-merge
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
      - name: Auto-merge Dependabot PR
        run: gh pr merge --auto --rebase "$PR_URL"
        env:
          PR_URL: "${{ github.event.pull_request.html_url }}"
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
