name: Flake

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update:
    name: Update
    runs-on: ubuntu-latest
    steps:
      - uses: cachix/install-nix-action@v18
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - uses: cachix/cachix-action@v11
        with:
          name: foosteros
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ssh-key: ${{ secrets.REPO_KEY }}

      - name: Configure git
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email '41898282+github-actions[bot]@users.noreply.github.com'

      - run: nix -vL --show-trace flake update

      - name: Commit changes
        run: |
          if ! git diff --exit-code --quiet flake.lock; then
            git commit -m "flake: update inputs" flake.lock
          fi

      - run: nix -vL --show-trace flake check

      - name: Push changes
        run: |
          git pull --rebase
          git push
