name: Flake

on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:
  update:
    name: Update
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.commit.outputs.changed }}
      head: ${{ steps.commit.outputs.head }}
    steps:
      - uses: cachix/install-nix-action@v20
        with:
          extra_nix_config: |
            system-features = benchmark big-parallel kvm nixos-test

      - uses: cachix/cachix-action@v12
        with:
          name: foosteros
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - uses: actions/checkout@v3
        with:
          ssh-key: ${{ secrets.REPO_KEY }}

      - name: Configure git
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email '41898282+github-actions[bot]@users.noreply.github.com'

      - run: nix -vL --show-trace flake update

      - id: commit
        name: Commit and stage changes
        run: |
          if ! git diff --exit-code --quiet flake.lock; then
            git commit -m 'flake: update inputs' flake.lock
            git push -f origin 'HEAD:ci/flake/${{ github.sha }}'

            echo 'changed=true' >> $GITHUB_OUTPUT
            echo 'head=ci/flake/${{ github.sha }}' >> $GITHUB_OUTPUT
          fi

      # TODO: remove whenever Nix (or crane) fixes this
      - name: 'TODO: Nix pls'
        run: |
          nix -vL build --no-link .#nixosConfigurations.bina.config.system.build.installBootLoader
        if: steps.commit.outputs.changed == 'true'

      - run: nix -vL --show-trace flake check --no-build
        if: steps.commit.outputs.changed == 'true'

  populate:
    name: Populate Checks Matrix
    runs-on: ubuntu-latest
    needs: [update]
    if: needs.update.outputs.changed == 'true'
    outputs:
      checks: ${{ steps.identify.outputs.checks }}
      cached: ${{ steps.query.outputs.cached }}
    steps:
      - uses: cachix/install-nix-action@v20
        with:
          extra_nix_config: |
            system-features = benchmark big-parallel kvm nixos-test

      - uses: actions/checkout@v3
        with:
          ref: '${{ needs.update.outputs.head }}'

      - id: identify
        name: Identify all system-compatible checks
        run: |
          echo "checks=$(nix -vL eval ".#checks.$(nix show-config --json | jq -r .system.value)" --apply builtins.attrNames --json)" >> $GITHUB_OUTPUT

  check:
    name: 'Check: ${{ matrix.check }}'
    runs-on: ubuntu-latest
    needs: [update, populate]
    if: needs.update.outputs.changed == 'true'
    strategy:
      matrix:
        check: ${{ fromJSON(needs.populate.outputs.checks) }}
    steps:
      - name: Free up runner space
        run: sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc

      - uses: cachix/install-nix-action@v20
        with:
          extra_nix_config: |
            system-features = benchmark big-parallel kvm nixos-test

      - uses: cachix/cachix-action@v12
        with:
          name: foosteros
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - uses: actions/checkout@v3
        with:
          ref: '${{ needs.update.outputs.head }}'

      - id: query
        name: 'Check cache for checks.${{ matrix.check }}'
        env:
          CHECK: ${{ matrix.check }}
        run: |
          narhash="$(nix -vL --show-trace eval --raw ".#checks.$(nix show-config --json | jq -r .system.value).$CHECK" --apply 'builtins.substring 11 32')"
          if curl -sfo /dev/null "https://foosteros.cachix.org/$narhash.narinfo"; then
            echo 'Found $narhash in cache'
            echo 'cached=true' >> $GITHUB_OUTPUT
          fi

      - id: build
        name: 'Build checks.${{ matrix.check }}'
        if: steps.query.outputs.cached != 'true'
        env:
          CHECK: ${{ matrix.check }}
        run: |
          nix -vL --show-trace build ".#checks.$(nix show-config --json | jq -r .system.value).$CHECK"

  push:
    name: Push
    runs-on: ubuntu-latest
    needs: [update, populate, check]
    if: needs.update.outputs.changed == 'true'
    steps:
      - uses: actions/checkout@v3
        with:
          ssh-key: ${{ secrets.REPO_KEY }}
          fetch-depth: 2
          ref: '${{ needs.update.outputs.head }}'

      - name: Push changes
        run: |
          git pull --rebase origin '${{ github.ref }}'
          git push origin 'HEAD:${{ github.ref }}'
          git push origin -d '${{ needs.update.outputs.head }}'
