name: Flake

on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:
  update:
    name: Update
    runs-on: ubuntu-latest
    steps:
      - uses: cachix/install-nix-action@v19
        with:
          extra_nix_config: |
            system-features = benchmark big-parallel kvm nixos-test

      - uses: cachix/cachix-action@v12
        with:
          name: foosteros
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ssh-key: ${{ secrets.REPO_KEY }}

      - name: Configure git
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email '41898282+github-actions[bot]@users.noreply.github.com'

      - run: nix -vL --show-trace flake update

      - id: commit
        name: Commit changes
        run: |
          if ! git diff --exit-code --quiet flake.lock; then
            git commit -m "flake: update inputs" flake.lock
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - run: nix -vL --show-trace flake check
        if: steps.commit.outputs.changed == 'true'

      - name: Push changes
        if: steps.commit.outputs.changed == 'true'
        run: |
          git pull --rebase
          git push
