name: Nix Impure

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  check:
    name: Run Checks
    uses: ./.github/workflows/checks.yml
    with:
      impure: true
