name: Nix

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  unstable-build:
    name: Unstable Build and Test
    runs-on: ubuntu-latest
    env:
      FOOSTEROS_EXCLUDE_UNFREE: 1
    steps:
      - uses: cachix/install-nix-action@v13
        with:
          install_url: https://github.com/numtide/nix-flakes-installer/releases/latest/download/install
          extra_nix_config: |
            experimental-features = nix-command ca-references flakes
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - uses: cachix/cachix-action@v10
        with:
          name: foosteros
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: nix -vL --show-trace build
      - run: nix -vL --show-trace flake check
      - run: nix -vL --show-trace store gc
        if: ${{ always() }}

  stable-build:
    name: Stable Build and Test
    runs-on: ubuntu-latest
    env:
      FOOSTEROS_EXCLUDE_UNFREE: 1
    steps:
      - uses: cachix/install-nix-action@v13
      - uses: cachix/cachix-action@v10
        with:
          name: foosteros
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: nix-build --show-trace
      - run: nix-build --show-trace --no-out-link test.nix
      - run: nix-store --show-trace --gc
        if: ${{ always() }}
