name: Nix

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  stable-flake-build:
    name: Stable Flake Build
    runs-on: ubuntu-latest
    steps:
      - uses: cachix/install-nix-action@v17
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - uses: cachix/cachix-action@v10
        with:
          name: foosteros
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - run: nix -vL --show-trace build

      - run: nix -vL --show-trace flake check

      - run: nix -vL --show-trace store gc
        if: ${{ always() }}

  stable-impure-build:
    name: Stable Impure Build
    runs-on: ubuntu-latest
    steps:
      - uses: cachix/install-nix-action@v17
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - uses: cachix/cachix-action@v10
        with:
          name: foosteros
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: nix-build --show-trace -E ...
        run: |
          nix-build --show-trace -E 'with (import <nixpkgs> {}).lib; unique (filter (drv: !drv.meta.unsupported && !drv.meta.unfree && (drv.meta ? dependsUnfree -> !drv.meta.dependsUnfree)) (collect (drv: isDerivation drv) (import ./. {})))'

      - run: nix-build --show-trace --no-out-link test.nix

      - run: nix-store --show-trace --gc
        if: ${{ always() }}

  unstable-flake-build:
    name: Unstable Flake Build
    runs-on: ubuntu-latest
    steps:
      - uses: cachix/install-nix-action@v17
        with:
          install_url: https://github.com/numtide/nix-unstable-installer/releases/latest/download/install
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - uses: cachix/cachix-action@v10
        with:
          name: foosteros
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - run: nix -vL --show-trace build

      - run: nix -vL --show-trace flake check

      - run: nix -vL --show-trace store gc
        if: ${{ always() }}
