name: Nix

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  check:
    name: Run Checks
    uses: ./.github/workflows/checks.yml
    secrets:
      cachix_auth_token: ${{ secrets.CACHIX_AUTH_TOKEN }}

  success:
    name: 'Success: Nix'
    runs-on: ubuntu-latest
    needs: [check]
    steps:
      - name: Check for success
        run: |
          echo 'All checks successfully completed!'
