name: Nix Unstable

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  check:
    name: Run Checks
    uses: ./.github/workflows/checks.yml
    with:
      nix_installer: https://github.com/nix-community/nix-unstable-installer/releases/latest/download/install

  success:
    name: Success
    runs-on: ubuntu-latest
    needs: [check]
    steps:
      - name: Check for success
        run: |
          echo 'All checks successfully completed!'
