name: Vim Plugins

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update:
    name: Update
    runs-on: ubuntu-latest
    env:
      FOOSTEROS_EXCLUDE_UNFREE: 1
    steps:
      - name: Free up runner space
        run: sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc
      - uses: cachix/install-nix-action@v16
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v10
        with:
          name: foosteros
      - uses: actions/checkout@v2
        with:
          ssh-key: ${{ secrets.REPO_KEY }}
      - name: Configure git
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email '41898282+github-actions[bot]@users.noreply.github.com'
      - run: pkgs/vim-plugins/update.py
      - name: Push changes
        run: |
          git pull --rebase
          git push
