name: Vim Plugins

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update:
    name: Update
    runs-on: ubuntu-latest
    steps:
      - uses: cachix/install-nix-action@v18
        with:
          extra_nix_config: |
            system-features = benchmark big-parallel kvm nixos-test

      - uses: cachix/cachix-action@v12
        with:
          name: foosteros

      - uses: actions/checkout@v3
        with:
          ssh-key: ${{ secrets.REPO_KEY }}

      - name: Configure git
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email '41898282+github-actions[bot]@users.noreply.github.com'

      - name: Configure $NIX_PATH
        run: |
          echo "NIX_PATH=nixpkgs=https://github.com/NixOS/nixpkgs/archive/$(jq -r '.nodes.nixpkgs.locked.rev' flake.lock).tar.gz" >> $GITHUB_ENV

      - id: update
        name: pkgs/vim-plugins/update.py
        run: |
          pkgs/vim-plugins/update.py

          if ! git diff --exit-code --quiet origin/${{ github.ref }}..; then
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - run: nix -vL --show-trace flake check
        if: steps.update.outputs.changed == 'true'

      - name: Push changes
        if: steps.update.outputs.changed == 'true'
        run: |
          git pull --rebase
          git push
