name: Vim Plugins

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    name: Update
    runs-on: ubuntu-latest
    env:
      FOOSTEROS_EXCLUDE_NONFREE: 1
    steps:
      - uses: actions/checkout@v2
        with:
          ssh-key: ${{ secrets.REPO_KEY }}
      - name: Configure git
        run: |
          git config user.name GitHub Actions
          git config user.email actions@github.com
      - uses: cachix/install-nix-action@v13
        with:
          nix_path: nixpkgs=channel:nixos-unstable:home-manager=https://github.com/nix-community/home-manager/archive/master.tar.gz:sops-nix=https://github.com/Mic92/sops-nix/archive/master.tar.gz
      - run: pkgs/vim-plugins/update.py
      - run: git push
